### ISSUE TITLE
Module not found after upgrade

### ISSUE THREAD

**Issue by Swoop86** [ottopaulsen/node-red-contrib-power-saver#13]
After upgrading to 3.0.0 (and now on 3.0.4), the palette view shows "MODULE_NOT_FOUND".
![image](https://user-images.githubusercontent.com/5503114/146034555-8b7ebcd6-5039-4e66-bea2-23c864845142.png)

**Comment by kristianrd** [comment]
I experience the same issue, version 3.0.2 and also after upgrade to 3.0.4

**Comment by ottopaulsen** [comment]
That may very well be the problem. A couple of dependencies where not correctly defined.
This should be fixed in version 3.0.5.
Please update when you have tried.

**Comment by Swoop86** [comment]
4 Dec 22:19:07 - [warn] ------------------------------------------------------
14 Dec 22:19:07 - [warn] [node-red-contrib-power-saver/ps-general-add-tariff] Error: Cannot find module '/config/node-red/node_modules/node-red-contrib-power-saver/src/general-add-tariff.js'
Require stack:
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
14 Dec 22:19:07 - [warn] ------------------------------------------------------

**Comment by kristianrd** [comment]
Yup, can confirm it works now.
Thanks a lot for the work you're putting in on this. Much appreciated!
